version: '3'
services:
  movies:
    image: yesdhan099/paytm4:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3

  train:
    image: yesdhan099/paytm4train:v1
    ports:
      - "92:80"
    deploy:
      replicas: 3

  dth:
    image: yesdhan099/paytm4dth:v1
    ports:
      - "93:80"
    deploy:
      replicas: 3

  recharge:
    image: yesdhan099/paytm4recharge:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3
